manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: niceviewflip
      url-base: https://github.com/invrtd
  projects:
    - name: zmk
      remote: niceviewflip
      revision: nive!view-180
      import: app/west.yml
  self:
    path: config
